### ISSUE TITLE
The Latest Release has a few issues.

### ISSUE THREAD

**Issue by MerlinisaG** [alberttheprince/rpemotes-reborn#32]
**Describe the bug**
The latest release has a few or more missing commas in AnimationList.lua and the version is incorrect in the fxmanifest.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on latest release '1.6.3'.
2. Install '1.6.3' and configure for your server.
3. Restart resource or server.
4. See errors.

**Expected behaviour**
The "Latest Release" shouldn't have these kind of issues.

**Additional context**
Can create PR with fixes.

**Comment by alberttheprince** [comment]
See my comments on your PR. If this was an issue with  https://github.com/alberttheprince/rpemotes-reborn/issues/29

It was fixed and 1.6.3 was reuploaded.

**Comment by alberttheprince** [comment]
The issues should be fixed with the latest version available in 1.6.3, your PR included an extra copy of the animation list as well. 

I think you had added some additional emotes from moustachedom, please PR those separately.

**Comment by MerlinisaG** [comment]
Yes that was un-intentional with the extra emotes, it was from a local copy from testing. If you see my multiple pushes and merge, it sort of explains it. I am fairly new to PR. 

So, the latest release is still broken. Same issue. Commas missing and the fxmanifest is incorrect.
