### ISSUE TITLE
Walk styles are not staying after restart or exiting server

### ISSUE THREAD

**Issue by Vividry** [alberttheprince/rpemotes-reborn#83]
I've followed the instructions, my sql is true/enabled in the config, i have it correct in the fxmanifest with the myoxsql, all boxes checked off. But walks aren't staying after the server restarts or the player logs out and back in. The player returns with the default walk.

![Image](https://github.com/user-attachments/assets/41499dfe-8741-45ff-9446-74ed68387e71)

![Image](https://github.com/user-attachments/assets/1800737f-c783-496d-a892-47aa2aeea714)

**Comment by alberttheprince** [comment]
@Mathu-lmn have you had any reports or experience with this issue? I know this was an issue in older versions of rpemotes, but I assumed it was fixed? Not sure if there was a regression.

**Comment by Daibolik** [comment]
i kown i have the same issue so i fix it on my side
Check this on your side, some stuff is wrote in french

```
local canChange = true
local unable_message = "Vous ne pouvez pas changer votre style de marche pour le moment."

function WalkMenuStart(name, force)
    if not canChange and not force then
        EmoteChatMessage(unable_message)
        return
    end

    if not name or name == "" then
        ResetWalk()
        return
    end

    if Config.PersistentWalk then
        SetResourceKvp("walkstyle", name) -- Sauvegarder le style
    end

    RequestWalking(name)
    SetPedMovementClipset(PlayerPedId(), name, 0.2)
    RemoveAnimSet(name)
end

function ResetWalk()
    if not canChange then
        EmoteChatMessage(unable_message)
        return
    end
    ResetPedMovementClipset(PlayerPedId(), 0.0)
end

function WalksOnCommand()
    local WalksCommand = ""
    for a in PairsByKeys(RP.Walks) do
        WalksCommand = WalksCommand .. string.lower(a) .. ", "
    end
    EmoteChatMessage(WalksCommand)
    EmoteChatMessage("Pour réinitialiser, utilisez /walk reset")
end

function WalkCommandStart(name)
    if not canChange then
        EmoteChatMessage(unable_message)
        return
    end
    name = FirstToUpper(string.lower(name))

    if name == "Reset" then
        ResetPedMovementClipset(PlayerPedId(), 0.0)
        DeleteResourceKvp("walkstyle")
        return
    end

    if TableHasKey(RP.Walks, name) then
        local name2 = table.unpack(RP.Walks[name])
        WalkMenuStart(name2)
    elseif name == "Injured" then
        WalkMenuStart("move_m@injured")
    else
        EmoteChatMessage("'" .. name .. "' n'est pas un style valide.")
    end
end

-- Persistance des styles de marche
if Config.WalkingStylesEnabled and Config.PersistentWalk then
    -- Vérifier si un style de marche existe
    local function walkstyleExists(kvp)
        for _, v in pairs(RP.Walks) do
            if v[1] == kvp then
                return true
            end
        end
        return false
    end

    -- Appliquer le style de marche sauvegardé
    local function handleWalkstyle()
        local kvp = GetResourceKvpString("walkstyle")

        if kvp ~= nil and kvp ~= "" then
            if walkstyleExists(kvp) then
                WalkMenuStart(kvp, true) -- Appliquer le style
            else
                ResetPedMovementClipset(PlayerPedId(), 0.0)
                DeleteResourceKvp("walkstyle")
            end
        end
    end

    -- Appliquer après le spawn
    AddEventHandler('playerSpawned', function()
        Wait(3000) -- Attente pour garantir que tout est chargé
        handleWalkstyle()
    end)
    RegisterNetEvent('QBCore:Client:OnPlayerLoaded', handleWalkstyle)
    RegisterNetEvent('esx:playerLoaded', handleWalkstyle)
end

if Config.WalkingStylesEnabled then
    RegisterCommand('walks', function() WalksOnCommand() end, false)
    RegisterCommand('walk', function(_, args, _) WalkCommandStart(tostring(args[1])) end, false)
    TriggerEvent('chat:addSuggestion', '/walk', 'Définir votre style de marche.', { { name = "style", help = "/walks pour une liste des styles valides" } })
    TriggerEvent('chat:addSuggestion', '/walks', 'Liste des styles de marche disponibles.')
end

exports('toggleWalkstyle', function(bool, message)
    canChange = bool
    if message then
        unable_message = message
    end
end)

exports('getWalkstyle', function()
    return GetResourceKvpString("walkstyle")
end)

exports('setWalkstyle', WalkMenuStart)
```

**Comment by alberttheprince** [comment]
> i kown i have the same issue so i fix it on my side Check this on your side, some stuff is wrote in french

Can you make a PR? If this is a fix, then please PR it so everyone can benefit from your fix. 👍

**Comment by Daibolik** [comment]
Its done you can check on your side

**Comment by Vividry** [comment]
After applying this my walk style did not even register. still not working on my end

**Comment by iSentrie** [comment]
> After applying this my walk style did not even register. still not working on my end

which walk style exactly?

**Comment by Daibolik** [comment]
I don't really know why its don't work on your side I have this in the config and fix the file and i test for 3 day for all player is working

![Image](https://github.com/user-attachments/assets/e43b354a-46f6-4ca7-b360-9a4776b21f1c)
